### PR TITLE
- Fixes scaling on android and added aspect ratio

### PR DESCRIPTION
**Pull request by ruerob**
Hello there!

I needed the option to keep the aspect ratio of the original image while scaling. I added this functionality to Android and iOS, I also tested it on my devices and hope it helps you as it helps me.
Also, this fixes issue 65 (https://github.com/fluttercandies/flutter_image_editor/issues/65) which prevents the pictures from being scaled to bigger sizes on Android.

Best wishes,
ruerob

### CODE REVIEW

**Comment by guihackmann** [comment]
Hi @ruerob,

To which package did you add this functionality? flutter_image_editor hasn't been updated since 2019.

**Comment by ruerob** [comment]
Hi @guihackmann! 

When I look into the commits at https://github.com/fluttercandies/flutter_image_editor/commits/master, the last update was on May 6, 2021. My change isn't approved by now, so it is not merged into the master branch.

One of the maintainers has to take a look into my changes and has to approve them in order to add the functionality into the master branch of this project.

**Comment by AlexV525** [comment]
@ruerob Hi, are you still on this track?

**Comment by ruerob** [comment]
Sorry for the long wait. I'm currently no longer on the flutter track. I haven't even installed Android Studio on my device.

**Comment by AlexV525** [comment]
> Sorry for the long wait. I'm currently no longer on the flutter track. I haven't even installed Android Studio on my device.

Thanks for let us know.

**Comment by AlexV525** [comment]
@ruerob I found a lot of branches you've created for the repo in your fork. I'm wondering if you may allow us to benefit from them if they help improve this plugin?

**Pull request merged**
