### PR TITLE
 - Fix file being written after the the future is finished

### PR DESCRIPTION
**Pull request by MoshDev**

### CODE REVIEW

**Comment by CaiJingLong** [comment]
The code here does have a problem, thanks PR.
But I still have some doubts about the flush parameter of this writeAsBytes method.

The annotation for this parameter is `writeAsBytes`: "If the argument [flush] is set to true, the data written will be flushed to the file system before the returned future completes ".

So,  I think use `file..writeAsBytesSync` is a good idea.

**Comment by MoshDev** [comment]
the file.. writeAsBytes will return 2 futures first one includes the file and the 2nd one is when the writeAsBytes is executed 

you cannot await both of them (since you don't have access to the 2nd one) which will cause the file is returned in the await and after that, it will writeAsBytes asynchronously 

you can try it by your self, writeAsBytes will create the file if it doesn't exists, so you can check if the file exists after calling the method and it will return false (most cases)

**Comment by MoshDev** [comment]
to simplify this
`return file..writeAsBytes(tmp);` will execute two things simultaneously 

1. returns `Future<File>` from the (`file`).
2. then asynchrounsly execute the `writeAsBytes(tmp);`

**Comment by CaiJingLong** [comment]
Maybe I didn't make it clear.
I don't have a question about one point and two points.
I have doubts about whether the flush parameter is called.

**Comment by MoshDev** [comment]
even you enabled flush= true this won't help

**Comment by CaiJingLong** [comment]
I mean, should you add the `flush: true` parameter based on your commit? No base my code, base your code.

**Comment by MoshDev** [comment]
there is no need to flush as the await for it from outside will make sure the data is written

**Comment by CaiJingLong** [comment]
I mean put aside your feelings. 
Just from the dart sdk's comments about the flush parameter in this method, do you think it should be added or not?

https://api.dart.dev/stable/2.7.0/dart-io/File/writeAsBytes.html
https://api.dart.dev/stable/2.7.0/dart-io/File/writeAsBytesSync.html

image

**Comment by CaiJingLong** [comment]
This is just a discussion, my opinion is to add the `flush: true` parameter to your code, because this is more in line with the purpose of this method.
But if you don't think it matters, then listen to you.

**Comment by MoshDev** [comment]
there is no need as the platform guarantees the file to be written, flush is useful when you are appending multiple data into the same file, in my opinion i dont see any usage of it

**Comment by CaiJingLong** [comment]
Thank you for your discussion.

**Comment by MoshDev** [comment]
Great library from you by the way

**Pull request merged**
